version: "3"
services:
  broker.choria:
    hostname: broker.choria
    image: docker.io/choria/choria:20220610
    dns_search: choria
    command: broker run --config /etc/choria/broker/broker.conf
    volumes:
      - ./config/broker:/etc/choria/broker
      - ./pki/broker:/etc/choria/pki
    networks:
      - choria

  provisioner.choria:
    hostname: provisioner.choria
    image: choria/provisioner:0.13.0
    dns_search: choria
    command: --config /etc/choria-provisioner/provisioner/provisioner.yaml --choria-config /etc/choria-provisioner/provisioner/choria.cfg
    volumes:
      - ./config/provisioner:/etc/choria-provisioner/provisioner
      - ./pki/provisioner:/etc/choria-provisioner/pki
    networks:
      - choria
    depends_on:
      - broker.choria

  server.choria:
    image: docker.io/choria/choria:20220610
    dns_search: choria
    command: server run --config /etc/choria/server.conf
    volumes:
      - ./pki/server/provisioning.jwt:/etc/choria/provisioning.jwt
    networks:
      - choria
    depends_on:
      - broker.choria

  aaa.choria:
    hostname: aaa.choria
    image: choria/aaasvc:0.6.0
    dns_search: aaa
    command: run --config /etc/aaasvc/aaa/aaa.conf
    volumes:
      - ./config/aaa:/etc/aaasvc/aaa
      - ./pki/aaa:/etc/aaasvc/pki
    networks:
      - choria
    depends_on:
      - broker.choria

  client.choria:
    hostname: client.choria
    image: docker.io/choria/choria:20220610
    dns_search: choria
    entrypoint: /bin/bash
    command: "-l"
    stdin_open: true
    tty: true
    volumes:
      - ./config/client:/etc/choria
      - ./pki/ca/ca.crt:/etc/choria-ca.pem
    networks:
      - choria
    depends_on:
      - broker.choria

networks:
  choria: {}
