version: "3"
services:
  broker.choria:
    hostname: broker.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    command: broker run --config /etc/choria/broker/broker.conf
    volumes:
      - ./config/broker:/etc/choria/broker
      - ./credentials/broker:/etc/choria/credentials
    networks:
      - choria

  provisioner.choria:
    hostname: provisioner.choria.local
    image: choria/provisioner:${PROV_TAG}
    dns_search: choria
    command: --config /etc/choria-provisioner/provisioner/provisioner.yaml --choria-config /etc/choria-provisioner/provisioner/choria.cfg
    volumes:
      - ./config/provisioner:/etc/choria-provisioner/provisioner
      - ./credentials/provisioner:/etc/choria-provisioner/credentials
    environment:
      - USER=choria
    networks:
      - choria
    depends_on:
      - broker.choria

  server.choria:
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    domainname: choria.local
    command: server run --config /etc/choria/server.conf
    volumes:
      - ./credentials/server/provisioning.jwt:/etc/choria/provisioning.jwt
      - ./config/server/machine:/etc/choria/machine
    networks:
      - choria
    depends_on:
      - broker.choria

  aaa.choria:
    hostname: aaa.choria.local
    image: choria/aaasvc:${AAA_TAG}
    dns_search: choria.local
    command: run --config /etc/aaasvc/aaa/aaa.conf
    environment:
      - USER=choria
    volumes:
      - ./config/aaa:/etc/aaasvc/aaa
      - ./credentials/aaasvc:/etc/aaasvc/credentials
    networks:
      - choria
    depends_on:
      - broker.choria

  client.choria:
    hostname: client.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    entrypoint: /bin/bash
    command: "-l"
    stdin_open: true
    tty: true
    volumes:
      - ./config/client:/etc/choria
    networks:
      - choria
    depends_on:
      - broker.choria

networks:
  choria: {}
