name: "aem_requests"
version: 1.0.0
initial_state: MANAGE

transitions:
  - name: enter_maintenance
    from: [ MANAGE ]
    destination: MAINTENANCE

  - name: resume
    from: [ MAINTENANCE ]
    destination: MANAGE

watchers:
  - name: download
    type: archive
    interval: "1m"
    state_match:
      - MANAGE
    properties:
      checksum: 5e73881403990220ad5e63a971fb3b8fd8299087439843d38d856d3be053fdc0
      verify_checksum: d3ebf8e4ae71245c051b9cb50f3712befbbc2c38c2cdf6e8e374eb7e613b1d11
      verify: SHA256SUMS
      source: "http://plugins.choria.local/requests-agent_0.0.1_linux_amd64.tar.gz"
      creates: "requests"
      target: "/var/lib/choria/plugins/mcollective/agent"

